### ISSUE TITLE
Describe an API

### ISSUE THREAD

**Issue by apocarteres** [TheGreatScraping/data-processing-engine#15]
We want to describe an API provided by DPE

**Comment by apocarteres** [comment]
Each cluster node provides REST service to accept user tasks to execute across the cluster.
This is description of very simple API which desirable to be implement by these REST services.

Each REST service contains bunch of contexts:
/ submit - allows user to submit tasks. Tasks must be checked in cluster topology.
- user must use POST request to submit the task.
- the task is being a string in JSON format, describes which task to execute and what are the parameters for that particular execution. 

Suppose that cluster contains the task known as <code>SimpleScrapingTask</code> and this task has two parameters <code>selector</code> and <code>url</code>

Using <code>/submit</code> the user can submit <code>SimpleScrapingTask</code> in follow manner:
```
{
  "task" : "SimpleScrapingTask",
  "args" : {
     "url" : "http://something.org"
     "selector" : "body"
  }
}
```

**Comment by rayhon** [comment]
check it, nice

We should put more info about 2 types of call. 
(1) sync call
(2) async call and for asyn call, there are callback vs poll

when a request is submitted, task id will be returned.
You can use another api to ping it for result periodically or you can have your callback for us to pass you the taskid when the task is done. So, you can do pull the result.

Currently, we cannot submit a task that is not pre-deployed. However, could that possible client get around this limitation via putting groovy script in the task instead. Just to brainstorm.. not necessarily we need to do that in this release.

**Comment by apocarteres** [comment]
i'm going to create a new version of API according to comments. Closing current issue
