### ISSUE TITLE
Create an abstraction from distributed technology

### ISSUE THREAD

**Issue by rayhon** [TheGreatScraping/data-processing-engine#2]
the data processing framework ideally should have an api to accept a pojo job and distributed it to >1 boxes for processing and return back results regardless what underneath distribution framework you used like storm or akka.

To do that, you may need to have abstraction layer to hide those technologies while provide an easy way for job submission and execution. So, we can start from defining how the api looks like first.

**Comment by apocarteres** [comment]
ok i will prepare a draft and we will discuss it

**Comment by apocarteres** [comment]
depends on #1

**Comment by apocarteres** [comment]
blocks #4
