### ISSUE TITLE
Get 3 linux boxes to run demo

### ISSUE THREAD

**Issue by apocarteres** [TheGreatScraping/data-processing-engine#5]
For running demo purposes it's needed to get access to 3 linux boxes to deploy parts of data processing application

**Comment by rayhon** [comment]
is it possible to use digitalocean?

**Comment by apocarteres** [comment]
yes it is. i'm using DO and it's a good service

**Comment by rayhon** [comment]
i already have account in linode. can we use it instead?

**Comment by apocarteres** [comment]
yes we can

**Comment by rayhon** [comment]
45.56.122.38
45.56.121.52
45.56.120.44

access via:
ssh root@[ip]
password is findology!
